In [9]:
import geopandas as gp
from shapely.geometry import Point, Polygon
import geojsonio
shp = gp.GeoDataFrame.from_file('world_m.shp')
shp = shp.to_json()
city_shp = gp.GeoDataFrame.from_file('cities.shp')
city_shp = city_shp.to_json()
geojsonio.display(city_shp,force_gist=True)

                 name                                       geometry
0        Vatican City    POINT (12.45338654497177 41.90328217996012)
1          San Marino      POINT (12.44177015780014 43.936095834768)
2               Vaduz    POINT (9.516669472907267 47.13372377429357)
3          Luxembourg    POINT (6.130002806227083 49.61166037912108)
4             Palikir    POINT (158.1499743237623 6.916643696007725)
5              Majuro    POINT (171.3800001757465 7.103004311216239)
6            Funafuti   POINT (179.2166470940289 -8.516651999041073)
7            Melekeok    POINT (134.6265484669922 7.487396172977981)
8              Monaco    POINT (7.406913173465057 43.73964568785249)
9              Tarawa    POINT (173.0175708285494 1.338187505624603)
10             Moroni   POINT (43.24024409869332 -11.70415769566847)
11            Andorra      POINT (1.51648596050552 42.5000014435459)
12      Port-of-Spain   POINT (-61.51703088544974 10.65199708957726)
13             Kigali    POINT (30.05858591906411 -1.95164421006325)
14            Mbabane   POINT (31.13333451205636 -26.31665077840921)
15               Juba    POINT (31.58002559278731 4.829975198277964)
16          Ljubljana     POINT (14.51496903347413 46.0552883087945)
17         Bratislava    POINT (17.11698075223461 48.15001832996171)
18               Doha     POINT (51.5329678942993 25.28655600890659)
19          Podgorica    POINT (19.26630692411823 42.46597251288171)
20               Bern    POINT (7.466975462482424 46.91668275866772)
21           Pristina    POINT (21.16598425159987 42.66670961411938)
22             Roseau   POINT (-61.38701298180337 15.30101564428332)
23           Djibouti    POINT (43.14800166705226 11.59501446425548)
24             Banjul    POINT (-16.5917014892126 13.45387646031594)
25             Skopje     POINT (21.4334614651425 42.00000612290586)
26         Bridgetown   POINT (-59.61652673505159 13.10200258275114)
27          Bujumbura    POINT (29.3600060615284 -3.376087220374643)
28          Kingstown   POINT (-61.21206242027932 13.14827882786841)
29           Castries   POINT (-61.00000818036955 14.00197348933034)
..                ...                                            ...
172         Amsterdam    POINT (4.914694317400972 52.35191454666443)
173             Seoul    POINT (126.9977851382019 37.56829495838895)
174            Manila    POINT (120.9802713035424 14.60610481344054)
175            Berlin    POINT (13.39960276470055 52.52376452225116)
176          Kinshasa   POINT (15.31302602317174 -4.327778243275986)
177         New Delhi    POINT (77.19998002005303 28.60002300924543)
178            Athens    POINT (23.73137522567936 37.98527209055226)
179           Baghdad    POINT (44.39192291456413 33.34059435615865)
180       Addis Ababa    POINT (38.69805857534868 9.035256221295754)
181            Tehran     POINT (51.42239817500899 35.6738886270013)
182      Buenos Aires  POINT (-58.39947723233144 -34.60055574990741)
183             Kabul    POINT (69.18131419070505 34.51863614490031)
184            Vienna    POINT (16.36469309674374 48.20196113681686)
185            Taipei      POINT (121.568333333333 25.0358333333333)
186  Washington, D.C.   POINT (-77.01136443943716 38.90149523508705)
187            London   POINT (-0.1186677024759319 51.5019405883275)
188            Riyadh    POINT (46.77079579868825 24.64277900781644)
189         Cape Town   POINT (18.43304229922603 -33.91806510862875)
190            Moscow     POINT (37.6135769672714 55.75410998124818)
191       Mexico City   POINT (-99.13293406029391 19.44438830141547)
192              Rome      POINT (12.481312562874 41.89790148509894)
193           Beijing    POINT (116.3863398256594 39.93083808990906)
194           Nairobi   POINT (36.81471100047145 -1.281400883237779)
195           Jakarta   POINT (106.8274917624701 -6.172471846798885)
196            Bogota   POINT (-74.08528981377441 4.598369421147822)
197             Cairo    POINT (31.24802236112612 30.05190620510371)
198             Tokyo    POINT (139.7494615705447 35.68696276437117)
199             Paris     POINT (2.33138946713035 48.86863878981461)
200          Santiago   POINT (-70.66898671317483 -33.4480679569341)
201         Singapore     POINT (103.853874819099 1.294979325105942)

[202 rows x 2 columns]